package com.c3s.blogs.Entity;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.springframework.stereotype.Component;

import java.util.List;


@Getter
@Setter
@ToString
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Component
@DynamoDBTable(tableName = "post")
public class BlogPost {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String text;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedJson
    private UserModel user;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedJson
    private Category category;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedJson
    private List<Comment> comment;


}
